export const SEARCH_JOBS_SUCCESS = "SEARCH_JOBS_SUCCESS";
export const GET_JOBS_TITLE_SUCCESS = "GET_JOBS_TITLE_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const SAVE_TEXT_SEARCH = "SAVE_TEXT_SEARCH";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";